//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SilcoSedonaInspectionApi
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Silco_FinalEntities1 : DbContext
    {
        public Silco_FinalEntities1()
            : base("name=Silco_FinalEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<CustSilco_AllInspForSiteServiceComp_Result> CustSilco_AllInspForSiteServiceComp(Nullable<int> siteid, Nullable<int> servicecompany)
        {
            var siteidParameter = siteid.HasValue ?
                new ObjectParameter("siteid", siteid) :
                new ObjectParameter("siteid", typeof(int));
    
            var servicecompanyParameter = servicecompany.HasValue ?
                new ObjectParameter("servicecompany", servicecompany) :
                new ObjectParameter("servicecompany", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CustSilco_AllInspForSiteServiceComp_Result>("CustSilco_AllInspForSiteServiceComp", siteidParameter, servicecompanyParameter);
        }
    }
}
